#Definimo constantes a utilizar en distintas funciones
ANCHO_VENTANA = 1000
ALTO_VENTANA = ANCHO_VENTANA*0.700
VENTANA_INICIAL = 'VENTANA INICIAL'
VENTANA_BATALLA = 'VENTANA BATALLA'
STRING_ELEGIR_EQUIPO = 'Elige el equipo a utilizar:\n\n'
STRING_ELEGIR_POK = 'Elige el pokemon a utilizar:\n\n'
STRING_ELEGIR_NOMBRE = 'Elige el nombre a utilizar para el jugador '
STRING_ELEGIR_OPCION = 'Elige lo que quieres hacer en este turno\n\n'
STRING_ELEGIR_MOV = 'Elige el movimiento a utlizar en este turno\n\n'
MENSAJE_NO_HAY_EQUIPOS = "¡No hay equipos! Vuelve la proxima"
MENSAJE_BATALLA_TERMINADA = "¡Gracias por jugar! ¡Hasta la proxima!"
IMAGEN_HOMBRE = 'assets//trainer1.gif'
IMAGEN_MUJER = 'assets//trainer2.gif'
OPCION_REALIZAR_MOVIMIENTO = 'REALIZAR_MOVIMIENTO'
OPCION_CAMBIAR_POKEMON = 'CAMBIAR POKEMON'
TITULO = 'Pokemon Showdown'
COLOR_NEGRO = 'black'
COLOR_GRIS = 'grey'
COLOR_VIOLETA_OSCURO = '#710380'
COLOR_VERDE = 'green'
COLOR_ROJO = 'red'
COLOR_AMARILLO = 'yellow'
UNO = '1'
DOS = '2'
TEXTO_EMPEZAR_BATALLA = '¡Presiona "Space" para empezar la batalla!'
FUENTE = 'MS Gothic'
TIPOS_DE_ATAQUES = ('Physical','Special')
OBJETIVOS = ('self' ,'normal', 'allAdjacent')
STATS_BOOSTERS = ('atk', 'def', 'spe', 'spa', 'spd')
COMENZAR_BATALLA = 'space'
AVANZAR_TURNO = 'space'
TEXTO_AVANZAR_TURNO = 'PRESIONA ESPACIO PARA\n\n   AVANZAR TURNO'
MENSAJE_SALIR = '¿Estas seguro que quieres salir de la batalla?\ns para confirmar\notro para cancelar'
DICCIONARIO_STATS= {'atk':'ATAQUE', 'spe': 'SPEED', 'def': 'DEFENSA'}
ICONO = 'assets/pokemon-showdown.gif'